export const endPoint = {
    USERS: '/Users',
    USERS_LOGIN: 'Users/Login',
    USERS_FILTER: 'Users/GetFilterUsers',
    USERS_GETBYLISTID: '/Users/GetByListID',
    USERS_GETBYID:'/Users/GetByID',
    USER_UPDATEPASS:'/Users/UpdatePassword',
    USERS_UPDATESTATUS:'/Users/UpdateStatus',
    USERS_MULTIPLEDELETE:'/Users/DeleteByListID',
    USERS_ADDTOTRASH:'/Users/AddToTrash',
    USERS_GETINTRASH:'/Users/GetUsersInTrash',
    PROJECT: '/Projects',
    PROJECT_UPDATE:'/Projects/UpdateByID',
    PROJECT_DELETEBYID:'/Projects/deleteByIntID',
    PROJECT_GETBYUSERID:'/Projects/GetByUserID',
    KANBAN:'/Kanbans',
    KANBAN_GETBYPROJECTID:'/Kanbans/GetKanbanByProjectID',
    KANBAN_DELETEBYID:'/Kanbans/deleteByIntID',
    KANBAN_UPDATE:'/Kanbans/UpdateByID',
    KANBAN_UPDATESORTORDER:'/Kanbans/UpdateSortOrder',
    TASK:"/Tasks",
    TASK_GETBYPROJECTID:'/Tasks/GetTaskByProjectID',
    TASK_UPDATE:"/Tasks/UpdateByID",
    TASK_UPDATEPROCESS:"/Tasks/UpdateProcess",
    TASK_UPDATEKANBAN:'/Tasks/UpdateKanban',
    TASK_DELETEBYID:'/Tasks/deleteByIntID',
    TASK_GETTASKTYPE:'/Tasks/GetTaskByType',
    TASK_GETUSERAMOUNTTASK:'/Tasks/GetUsersAmountTask'
  }